### ISSUE TITLE
Funky label when editing records

### ISSUE THREAD

**Issue by afred** [WGBH/hydradam#21]
**Done when**
We change this label to be something more meaningful -- OR -- we conclude that the label is actually correct.

![image](https://cloud.githubusercontent.com/assets/1507490/5946744/2770a570-a706-11e4-99c9-1a99ce5442db.png)

**Comment by Muraszko** [comment]
@afred 
I'm fine with changing the label or removing it all together.  It's referring to a MARS field in the Logs section, but it's also one of those "catch all" fields that often has multiple file names listed within it.
The file name automatically becomes part of the record in HydraDAM upon import, so this would be potentially less accurate anyway because of human error.

**Comment by afred** [comment]
:+1: for removal then

**Comment by mccalluc** [comment]
Dumb question, but where does this come from? Should I be trying a different string?
```
[hydradam]$ grep 'digitial file name' -r .
[hydradam]$ grep 'digitial file name' -r ~/.rvm/gems/ruby-2.0.0-p481/gems/hydra-pbcore-3.3.1
[hydradam]$ grep 'digitial file name' -r ~/.rvm/gems/ruby-2.0.0-p481/gems/sufia-4.0.0
```

**Comment by afred** [comment]
don't know off hand. Maybe start with the form and work backward?

**Comment by mccalluc** [comment]
Trying to get started:
```
> Rails.application.routes.recognize_path '/files/g445cf10p'
ActionController::RoutingError: No route matches "/files/g445cf10p"
```

**Comment by afred** [comment]
I've never used `Rails.application.routes.recognize_path` before. Looks like it might be [deprecated](http://apidock.com/rails/ActionController/Routing/RouteSet/recognize_path)?

Running `rake routes` on my local machine, I see:
```
...
             citation_generic_file GET      /files/:id/citation(.:format)                    generic_files#citation
                audit_generic_file POST     /files/:id/audit(.:format)                       generic_files#audit
                     generic_files POST     /files(.:format)                                 generic_files#create
                  new_generic_file GET      /files/new(.:format)                             generic_files#new
                 edit_generic_file GET      /files/:id/edit(.:format)                        generic_files#edit
                      generic_file GET      /files/:id(.:format)                             generic_files#show
                                   PATCH    /files/:id(.:format)                             generic_files#update
                                   PUT      /files/:id(.:format)                             generic_files#update
                                   DELETE   /files/:id(.:format)                             generic_files#destroy
...
```
.. which shows me that Sufia is getting it's routes in there somewhere.

**Comment by mccalluc** [comment]
That was educational, but totally the wrong path. Sorry. PR incoming.
![screen shot 2015-03-03 at 1 01 13 pm](https://cloud.githubusercontent.com/assets/730388/6468775/7364c4e8-c1a5-11e4-8bfa-7e84e84a81ef.png)
