### ISSUE TITLE
Select all button missing from dashboard page

### ISSUE THREAD

**Issue by Muraszko** [WGBH/hydradam#43]
While on the Dashboard page, if I'm setting it to view 100 items per page, the "Select All" button is missing from the top of the list.

**DONE WHEN**
The button is being correctly displayed while showing 100 records per page.

**Comment by mccalluc** [comment]
@Muraszko : This is by design, and it's in Sufia: 
{sufia}/app/views/batch_edits/_check_all.html.erb:
```
<%= check_box_tag 'check_all', 'yes', @all_checked, :disabled => ((@batch_size_on_other_page + @document_list.count) > @max_batch_size) %>
```
Options:
- do nothing.
- override this partial just for wgbh, removing the disabled flag.
- up the batch size, just for wgbh.
- something else?

**Comment by Muraszko** [comment]
Since the restriction is something that appears to be deliberate in the code for some reason, we will leave it in until a user gives us reason to change it.  Closing.
