### ISSUE TITLE
File Path Field Not Working Correctly

### ISSUE THREAD

**Issue by Muraszko** [WGBH/hydradam#8]
On asset records, under the File Details is the field, File Path.  When importing from a folder, it looks as though it's retaining the file path information, but when importing an individual file, the field is blank.

DONE WHEN:
The complete file path information is retained in the record after ingest.

**Comment by mccalluc** [comment]
@Muraszko:
- I only seem to be able to upload single files.
- And "File Path" is just blank.

Are these regressions, or am I looking at the wrong thing?

**Comment by Muraszko** [comment]
Use Google Chrome when using the web browser UI.

**Comment by mccalluc** [comment]
(Bugs tracking discussion of this feature in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=876480 https://bugzilla.mozilla.org/show_bug.cgi?id=846931)
